'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, Loader2, RefreshCw } from 'lucide-react';
import { useParams } from 'next/navigation';
import { toast } from 'sonner';
import { PageHeader } from '@/components/ui/page-header';
import { api } from '@/lib/api';
import type { Account, SportWorldRunRecord } from '@/lib/types';
import { formatDate, formatDistance } from '@/lib/utils';

function sport(a: Account) { return a.sport_world_accounts ? (Array.isArray(a.sport_world_accounts) ? a.sport_world_accounts[0] : a.sport_world_accounts) : null; }
function legacyCompleted(a: Account) { const p = a.progress; return Array.isArray(p) ? p[0]?.completed_runs || 0 : p?.completed_runs || 0; }
export default function ProgressDetailPage() {
  const params = useParams<{ id: string }>(); const id = params.id; const [account, setAccount] = useState<Account | null>(null); const [records, setRecords] = useState<SportWorldRunRecord[]>([]); const [loading, setLoading] = useState(true); const [valid, setValid] = useState('');
  async function load() { setLoading(true); try { const [progress, history] = await Promise.all([api<{ accounts: Account[] }>('/api/progress'), api<{ records: SportWorldRunRecord[]; total: number }>(`/api/accounts/${id}/sport-world-records?valid=${valid}`)]); setAccount(progress.accounts.find((item) => item.id === id) || null); setRecords(history.records); } catch (error) { toast.error(error instanceof Error ? error.message : '加载详情失败'); } finally { setLoading(false); } }
  useEffect(() => { if (id) load(); }, [id, valid]);
  const binding = account ? sport(account) : null; const hasBinding = Boolean(binding?.sport_account); const done = account ? (hasBinding ? Math.max(0, Number(binding?.completed_runs || 0) + Number(binding?.manual_run_adjustment || 0)) : legacyCompleted(account)) : 0; const syncedDistance = hasBinding ? Math.max(0, Number(binding?.completed_distance || 0) + Number(binding?.manual_distance_adjustment || 0)) : 0; const distance = account ? (syncedDistance || account.distance_per_run * done) : 0;
  return <><PageHeader title="进度详情" description={account ? `${account.school?.name || '未设置'} / ${account.username}` : '正在加载'} action={<div className="flex gap-2"><Link className="btn-secondary" href="/progress"><ArrowLeft className="h-4 w-4" />返回进度</Link><button className="btn-secondary" onClick={load}><RefreshCw className="h-4 w-4" />刷新</button></div>} />{loading && !account ? <div className="card py-20 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin text-brand-500" /></div> : account ? <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Summary label="目标次数" value={`${account.order_count} 次`} /><Summary label="已跑次数" value={`${done} 次`} /><Summary label="剩余次数" value={`${Math.max(0, account.order_count - done)} 次`} /><Summary label="目标公里数" value={formatDistance(account.distance_per_run * account.order_count)} /><Summary label="已完成公里数" value={formatDistance(distance)} /><Summary label="剩余公里数" value={formatDistance(Math.max(0, account.distance_per_run * account.order_count - distance))} /><Summary label="当前学期" value={binding?.current_semester || '—'} /><Summary label="最后同步" value={formatDate(binding?.last_sync_at)} /></div><div className="card mt-6 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-4"><h2 className="font-semibold">跑步记录</h2><select className="input w-auto" value={valid} onChange={(event) => setValid(event.target.value)}><option value="">全部状态</option><option value="true">有效</option><option value="false">无效</option></select></div>{records.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">日期</th><th className="px-4 py-3">开始时间</th><th className="px-4 py-3">公里数</th><th className="px-4 py-3">运动时长</th><th className="px-4 py-3">配速</th><th className="px-4 py-3">有效状态</th><th className="px-4 py-3">运动类型</th></tr></thead><tbody className="divide-y divide-slate-100">{records.map((record) => <tr key={record.id}><td className="px-4 py-3">{record.run_date || '—'}</td><td className="px-4 py-3 text-xs text-slate-500">{formatDate(record.start_time)}</td><td className="px-4 py-3 font-semibold">{formatDistance(record.distance)}</td><td className="px-4 py-3">{record.duration ? `${Math.round(record.duration / 60)} 分钟` : '—'}</td><td className="px-4 py-3">{record.pace ? `${record.pace}` : '—'}</td><td className="px-4 py-3">{record.is_valid ? <span className="text-emerald-600">有效</span> : <span className="text-slate-400">无效</span>}</td><td className="px-4 py-3">{record.sport_type || '—'}</td></tr>)}</tbody></table></div> : <div className="py-16 text-center text-sm text-slate-400">暂无跑步记录</div>}</div></> : <div className="card py-20 text-center text-sm text-slate-400">账号不存在</div>}</>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="card p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>; }
